http://localhost:3000

###

http://localhost:3000/books?minPrice=200&maxPrice=300


###

http://localhost:3000/books/73cb280c-f02c-48e7-ae41-d9cd16061d79


### bad book id
http://localhost:3000/books/123


### POST a book
POST http://localhost:3000/books
content-type: application/json

{
  "title": "junk",
  "author": "F. Scott Fitzgerald",
  "genre": "Fiction",
  "price": 11.50
}


### decoy
http://localhost:3000/fake/1